packages:
  - apps/*

allowBuilds:
  deno: false
  esbuild: true
  sqlite3: true

ignoredBuiltDependencies:
  - deno

minimumReleaseAgeExclude:
  - '@melledijkstra/*'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sqlite3
