packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^6.0.3
  eslint: ^10.8.0
  '@types/node': ^25.9.5
  'react': ^19.2.8
  'react-dom': ^19.2.7
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.3
  eslint-plugin-turbo: ^2.10.7
  prettier: ^3.9.6
  prettier-plugin-svelte: ^4.1.1
  prettier-plugin-tailwindcss: ^0.8.1
  eslint-config-prettier: ^10.1.8
  tsx: ^4.23.1
  vitest: ^4.1.10

allowBuilds:
  better-sqlite3: true
  deno: false
  esbuild: true
  sqlite3: true

ignoredBuiltDependencies:
  - deno

minimumReleaseAgeStrict: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sqlite3
